### ISSUE TITLE
clinkz flaming arrows are passive but drows frost arrows not

### ISSUE THREAD

**Issue by sercankd** [fcalife/dota_imba#50]
this leads unequality between those two heroes, when clinkz silenced he continues with flaming arrows but drow have no similarity

**Comment by fcalife** [comment]
This is because of an inability to make Orb-based abilities work on spell-immune or building targets. You can see the struggle if you look at the recent changes to Tidebringer.

Basically, since Drow's arrows aren't supposed to work on magic immune/buildings in the first place, they're fine; but Clinkz's are not. Thus, the passive ability workaround.

If anyone can provide a way to make orbs work on magic immune/buildings, I'd merge it on the spot; otherwise, I'll just fix it way down the line, after I start converting some relevant abilities to lua-based.

Best regards!

**Comment by Shushishtok** [comment]
I'm closing this issue since we've decided to keep the mana drain from Drow's Frost Arrows, while changing the active ability of Searing Arrows, which now has a mana cost of its own, unrelated to vanilla Dota.
This increases the difference of Searing Arrows and Frost Arrows, as Searing Arrows are now absolutely intended to be a passive skill.

Thank you for the report!
