### ISSUE TITLE
Abaddon Rework

### ISSUE THREAD

**Issue by X-TheDark** [fcalife/dota_imba#510]
ABADDON:

MIST COIL: Adds a mist to the target. The mist lingers over an ally target. At the end of the duration, the mist heals a percentage of the damage taken during that time.
If cast on an enemy, the mist become volatile, dealing a small magical damage to it each time it takes damage.
Mist lasts 2 seconds.

When Abaddon dies, a Mist Coil is cast on all allies and enemies in 900 AoE.

APHOTIC SHIELD: Casting Mist Coil on an ally that is already shielded by Aphotic Shield increases the duration by 3 seconds and fully refreshes the health of the shield.
When the shield explodes by any means, it applies a basic purge on allies and enemies in the blast AoE.

Cooldown reverted to vanilla cooldown, shield's capacity increased.

OVERCHANNEL: Now a no target, no mana, no cast point, can be used through stuns spell. Has 3 seconds cooldown. Using it grants the user the Overchannel buff. The buff increases the power of the next spell at the cost of health (similar to how it worked up to now, no changes in values as well), then disappears.
If the caster has the talent that grants an active component to Curse of Avernus and it is off cooldown, his next attack consumes the Overchannel buff and doubles the health cost and the damage of the attack. 

When the buff is ready to be used, also increases Mist Coils' Mist's duration by 2 seconds, and increases the shield's capacity by 75.

---------------------------------
TALENTS:

Remove:
Shield of the Seer (+45 seconds Aphotic Shield duration)
Far-Reaching Mist (+150 Mist Coil cast range)
Overflowing Mist (-1.5 Mist Coil CD)
The Long Arm of Avernus (+300 Borrowed Time AoE)
Late Payment (+1 Borrowed Time duration)
Aphotic Bulwark (+200 shield capacity)
Blessing of Avernus (+5% move speed, +30 attack speed on Curse of Avernus)

Apply:
1. Heals that heal above maximum health threshold during Borrowed Time grants a mist shield (25% ratio) that is released after Borrowed Time expires for 5 seconds, healing Abaddon.
2. Aphotic Shield - When the shield breaks, applies Mist Coil to all allies and enemies within 350 radius.
3. During the first second of Aphotic Shield, it absorbs all damage done to it and adds it to it's health/damage.
4. Borrowed Time Strong Purges all allies in 900 AoE on cast.
5. Curse of Avernus Abbadon buff now apply as an aura around him in 900 AoE, affecting all allies in range.
6. Curse of Avernus can now be activated to sacrifice a 10% of your current health, and deal it as extra damage on the next attack. Has a 8 seconds cooldown.
7. Consecutives hits of Curse of Avernus refreshes the buff/debuff and increases the duration of the buff/debuff by 1 second.

**Comment by Fcalifedev** [comment]
Might I suggest a slight mechanical rework:

Make over channel an active, no-target, no cast point, no cool down, no mana cost ability, which can be used through stuns (ignores pseudo queue).

Instead of it being an on/off toggle, it simply grants you an over channel buff, which causes the next spell you cast to receive over channel's effects. After using said spell, you lose over channel's effects.

Make it so auto attacking with the buff on counts as an activation of "Curse of Avernus" (talent #6), triggering its cool down. Autoattacking while the spell is on cool down would, obviously, do nothing extra, and also not consume the over channel buff. That way, all of Abaddon's basic abilities are now affected by overchannel, which is more elegant design in my opinion.

------------

Alternatively, even if you opt to keep the ability as a toggle, or curse's extra effects as a talent, make it so curse of avernus' "active" effect triggers if overchannel is toggled on (and doesn't do so if it is turned off). I think this ties abandon's whole kit better overall.

Best regards!

**Comment by fcalife** [comment]
Might I suggest a slight mechanical rework:

Make over channel an active, no-target, no cast point, no cool down, no mana cost ability, which can be used through stuns (ignores pseudo queue).

Instead of it being an on/off toggle, it simply grants you an over channel buff, which causes the next spell you cast to receive over channel's effects. After using said spell, you lose over channel's effects.

Make it so auto attacking with the buff on counts as an activation of "Curse of Avernus" (talent #6), triggering its cool down. Autoattacking while the spell is on cool down would, obviously, do nothing extra, and also not consume the over channel buff. That way, all of Abaddon's basic abilities are now affected by overchannel, which is more elegant design in my opinion.

------------

Alternatively, even if you opt to keep the ability as a toggle, or curse's extra effects as a talent, make it so curse of avernus' "active" effect triggers if overchannel is toggled on (and doesn't do so if it is turned off). I think this ties abandon's whole kit better overall.

Best regards!

**Comment by Shushishtok** [comment]
I love,it. This is a good idea, and removes the "toggle and forget" behavior of the current Overchannel.

I'll edit the concept.
