### ISSUE TITLE
Axe Rework

### ISSUE THREAD

**Issue by X-TheDark** [fcalife/dota_imba#513]
Battle Hunger:
Removes infinite duration.
Duration is now paused when the target doesn't deal damage for 2 seconds. (debuff is still removed on fountain).
Whenever the target attemps to attack, it has 25% chance to attack another target instead, unless the target is Axe. The other target can be either its ally or enemy. For the duration of the attack (depends on its attack speed), the target cannot issue commands.

Counter Helix:
Each time Axe spins, the spin radius increases by 15, up to 5 stacks. Stacks are refreshed on a successful spin and last 4 seconds.
For each taunted enemy around you when you spin, increases the bonus damage percentage.

Culling Blade:
Can cull a target if it has health below the threshold, or has lower than 15% max health. On a successful culling, increases the kill threshold by 100 and the max health threshold by 5%. This buff immediately ends if failing a Culling. Stacks are refreshed and last 60 seconds. Culling Blade can maintain up to 5 stacks. (otherwise the next stack just refreshes).

---------------------------------------------

TALENTS:
Remove:
+90 Berserker Call radius.
+90 Counter Helix radius.
+100 Battle Hunger DPS.
+150 attack speed on Berserker Call.
+400 Culling Blade threshold.

Apply: 
1. Self-Casting W applies it to everyone affected by Q.
2. If an enemy unit with Battle Hunger attacks an ally, that ally also gains the Battle Hunger debuff.
3. Counter Helix chance doubles, but each Counter Helix deals 66% of the original damage.
4. When Counter Helix procs, it has 25% chance to immediately proc again. Psuedo Random chance. The extra proc cannot trigger this again.
5. Counter Helix's damage is increased by 1 for each point of Armor Axe has.

**Comment by fcalife** [comment]
Suggestions:

- make W's cast point much quicker while Q is active (or instant);
- talents 3, 4 and 5 seem really weak (4 a bit less weak but essentially a 25% damage increase to helix);
- Cull stacks need a threshold, even if the situation where it would become excessive seems rare. I'd suggest a cap of 5 stacks.

**Comment by Shushishtok** [comment]
I agree with capping Culling Blade.

>make W's cast point much quicker while Q is active (or instant);
I'm not sure what is exactly the point of having a hasted Battle Hunger. You usually cast in on heroes that are a bit further away of you, and it can be used while spinning. In addition, taking the first talent (cast W on self) already has an immense effect.

>talents 3, 4 and 5 seem really weak (4 a bit less weak but essentially a 25% damage increase to helix);

Talent 3 is a talent that was practically popular because it turns Axe into an helicopter. I can probably make the damage loss a 1/3 instead. (-33% damage).

Talent 4 works well with talent 3, otherwise yes, it's pretty much a damage bonus.

Talent 5: I think you're underestimating it. When you're using Q, you get 100 armor. Having +100 damage *per* Counter Helix, especially combined with the double proc chance, can be very deadly.

**Comment by fcalife** [comment]
Yeah I totally forgot q armor, good one

**Comment by natanfudge** [comment]
> If an enemy unit with Battle Hunger attacks an ally, that ally also gains the Battle Hunger debuff.

The fuck is this
