### ISSUE TITLE
Bounty Hunter Rework

### ISSUE THREAD

**Issue by X-TheDark** [fcalife/dota_imba#516]
Headhunter: contracted enemy is shown to Bounty Hunter once every 10 seconds for 1 second.
Vision radius from 300 to 600.

-------------------------------------

TALENTS:
Remove:
+15%/+15 movespeed/attackspeed reduction on Jinada.
+200 True Sight range in Shadow Walk.
-2 Track cooldown.
+75 Shuriken Toss damage.
+30 Track duration.
-5 Jinada cooldown.

Apply:
1. Tracked enemies take 20% more damage from any source.
2. Tracked enemies grant normal vision instead of fogvision for the duration. The vision has a 600 AoE radius. 
3. Jinada can now be cast on allies, granting them the ensured Jinada buff. The buff lasts 10 seconds, or until the attacker fires an attack once.
4. If Jinada is off cooldown, Shuriken Toss procs it. The shuriken deals bonus critical damage and applies the Jinada slow debuff on all enemies hit.
5. When Bounty Hunter is in Shadow Walk, he gains 1% move speed per second as long as he's actively moving. Staying in the same place for more than one second instantly removes the buff. The move speed cap is increased by the same amount of the move speed Bounty Hunter gains through this talent.
6. Jinada's Shadow Jaunt can be cast on contracted enemies up to 2500 units away.

**Comment by fcalife** [comment]
comments/suggestions:

- I hope talents 1 and 2 are a binary choice (i.e. can only take one of them), because they're both *really* strong. One wouldn't break track, but I feel like both at the same time would.
- talent 3 has potentially *insane* implications, but it's so cool...
- talent 4 requires good use of projectile_extradata, please be aware of that when coding it.
- talent 5 is pretty cool but goes against a "tracking" archetype (trackers usually stay in place for long of periods of time, waiting for their prey). If you want to go for rule of cool, sure, but I'd make it grant bonuses the longer you have stayed still, instead. This goes well with shadow jaunt, too. Imagine: stay in place, invisible, for 30 seconds. Enemy comes in range, track him, jaunt, have a huge ms buff for a while (˜3-6 sec) because of the time you spent waiting. Alternatively, make invisible not count down while BH isn't moving.
- 2500 is *really* a lot. beware of mobility creep.

**Comment by Shushishtok** [comment]
>I hope talents 1 and 2 are a binary choice (i.e. can only take one of them), because they're both really strong. One wouldn't break track, but I feel like both at the same time would.

You're right. Yep, they should be a binary choice.

>talent 3 has potentially insane implications, but it's so cool...

I love it. I don't mind people finally buffing each other for a change.

>talent 4 requires good use of projectile_extradata, please be aware of that when coding it.

It's actually not that bad. Just adds a variable to it. Shuriken already uses projectile_extradata because of the scepter effect.

>talent 5 is pretty cool but goes against a "tracking" archetype (trackers usually stay in place for long of periods of time, waiting for their prey). If you want to go for rule of cool, sure, but I'd make it grant bonuses the longer you have stayed still, instead. This goes well with shadow jaunt, too. Imagine: stay in place, invisible, for 30 seconds. Enemy comes in range, track him, jaunt, have a huge ms buff for a while (˜3-6 sec) because of the time you spent waiting. Alternatively, make invisible not count down while BH isn't moving.

While I agree logically, most players aren't that patient. They move a lot, position themselves in various location, and this helps achieve this goal, especially because Track can be cast through invisibility. I think it's fine.

>2500 is really a lot. beware of mobility creep.

Agreed. Will keep it for now. It only triggers on Headhunter targets, which is one random enemy hero that is chosen on fountain - this is pretty rare, which is why I think amping it like that is reasonable.

**Comment by Shushishtok** [comment]
Done!
